target 'DesafioKabum' do
  pod 'Alamofire'
  pod 'SDWebImage', :modular_headers => true
end

target 'DesafioKabumTests' do
  pod 'Alamofire'
  pod 'SDWebImage', :modular_headers => true
end

post_install do |installer|
    installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.4'
               end
          end
   end
end
